apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: evilpetclinic
  name: evilpetclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evilpetclinic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: evilpetclinic
    spec:
      containers:
      - image: rbenavente/evilpetclinic:latest
        name: evilpetclinic
        resources: {}
      imagePullSecrets:
      - name: regcred
status: {}
